// haven-cli — operational and administrative CLI for Haven.
// Provides unattended setup, secret generation, health checks, and factory reset.
package main

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
)

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	if len(args) == 0 {
		printUsage()
		return nil
	}

	switch args[0] {
	case "setup":
		// TODO: --unattended flag reads HAVEN_OWNER_* env vars and calls the setup API
		return fmt.Errorf("setup: not implemented")

	case "generate-secrets":
		return generateSecrets()

	case "validate-config":
		// TODO: --env-file flag, load config, print OK or errors
		return fmt.Errorf("validate-config: not implemented")

	case "healthcheck":
		// TODO: call GET /health, exit 0 on 200, exit 1 otherwise
		return fmt.Errorf("healthcheck: not implemented")

	case "factory-reset":
		// TODO: require --confirm-destroy-all-data flag
		//       drop haven schema and recreate, reset state to UNCLAIMED
		return fmt.Errorf("factory-reset: not implemented")

	default:
		printUsage()
		return fmt.Errorf("unknown command: %s", args[0])
	}
}

func generateSecrets() error {
	jwtKey, err := randomHex(64) // 512-bit signing key
	if err != nil {
		return fmt.Errorf("generate jwt key: %w", err)
	}
	dbPass, err := randomHex(32) // 256-bit DB password
	if err != nil {
		return fmt.Errorf("generate db password: %w", err)
	}

	fmt.Printf("# Generated by: go run ./cmd/cli generate-secrets\n")
	fmt.Printf("# Copy these into your .env file.\n\n")
	fmt.Printf("HAVEN_JWT_SIGNING_KEY=%s\n", jwtKey)
	fmt.Printf("HAVEN_DB_PASS=%s\n", dbPass)
	return nil
}

func randomHex(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

func printUsage() {
	fmt.Println(`haven-cli — Haven IAM administration

Commands:
  setup [--unattended]              Full unattended install (reads HAVEN_OWNER_* env vars)
  generate-secrets                  Print all required secrets as .env lines
  validate-config [--env-file FILE] Validate configuration before starting
  healthcheck                       Exit 0 if server is healthy
  factory-reset --confirm-destroy-all-data
                                    Wipe all data and reset to UNCLAIMED state`)
}
