// haven-cli — operational and administrative CLI for Haven.
// Provides unattended setup, secret generation, health checks, and factory reset.
package main

import (
	"bufio"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"net/http"
	"os"
	"strings"

	"github.com/josephtindall/haven/pkg/config"
)

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	if len(args) == 0 {
		printUsage()
		return nil
	}

	switch args[0] {
	case "setup":
		// TODO: --unattended flag reads HAVEN_OWNER_* env vars and calls the setup API
		return fmt.Errorf("setup: not implemented")

	case "generate-secrets":
		return generateSecrets()

	case "validate-config":
		return validateConfig(args[1:])

	case "healthcheck":
		return healthcheck(args[1:])

	case "factory-reset":
		// TODO: require --confirm-destroy-all-data flag
		//       drop haven schema and recreate, reset state to UNCLAIMED
		return fmt.Errorf("factory-reset: not implemented")

	default:
		printUsage()
		return fmt.Errorf("unknown command: %s", args[0])
	}
}

func validateConfig(args []string) error {
	// Parse --env-file flag.
	var envFile string
	for i, a := range args {
		if a == "--env-file" && i+1 < len(args) {
			envFile = args[i+1]
		}
	}

	if envFile != "" {
		if err := loadEnvFile(envFile); err != nil {
			return fmt.Errorf("validate-config: %w", err)
		}
	}

	cfg, err := config.Load()
	if err != nil {
		return fmt.Errorf("validate-config: %w", err)
	}

	fmt.Println("Configuration OK")
	fmt.Printf("  Port:      %s\n", cfg.Port)
	fmt.Printf("  DB host:   %s:%s/%s\n", cfg.DBHost, cfg.DBPort, cfg.DBName)
	fmt.Printf("  Redis:     %s\n", cfg.RedisAddr)
	fmt.Printf("  JWT key:   %d bytes\n", len(cfg.JWTSigningKey))
	return nil
}

// loadEnvFile reads a .env file and sets each key=value pair into the environment.
// Lines starting with '#' and blank lines are ignored.
func loadEnvFile(path string) error {
	f, err := os.Open(path)
	if err != nil {
		return fmt.Errorf("open env file: %w", err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		idx := strings.IndexByte(line, '=')
		if idx < 0 {
			continue
		}
		key := line[:idx]
		val := line[idx+1:]
		if err := os.Setenv(key, val); err != nil {
			return fmt.Errorf("setenv %s: %w", key, err)
		}
	}
	return scanner.Err()
}

func healthcheck(args []string) error {
	addr := "http://127.0.0.1:8080"
	for i, a := range args {
		if a == "--addr" && i+1 < len(args) {
			addr = args[i+1]
		}
	}

	resp, err := http.Get(addr + "/api/haven/health") //nolint:gosec
	if err != nil {
		fmt.Fprintf(os.Stderr, "healthcheck: request failed: %v\n", err)
		os.Exit(1)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		fmt.Fprintf(os.Stderr, "healthcheck: unexpected status %d\n", resp.StatusCode)
		os.Exit(1)
	}
	fmt.Println("healthy")
	return nil
}

func generateSecrets() error {
	jwtKey, err := randomHex(64) // 512-bit signing key
	if err != nil {
		return fmt.Errorf("generate jwt key: %w", err)
	}
	dbPass, err := randomHex(32) // 256-bit DB password
	if err != nil {
		return fmt.Errorf("generate db password: %w", err)
	}

	fmt.Printf("# Generated by: go run ./cmd/cli generate-secrets\n")
	fmt.Printf("# Copy these into your .env file.\n\n")
	fmt.Printf("HAVEN_JWT_SIGNING_KEY=%s\n", jwtKey)
	fmt.Printf("HAVEN_DB_PASS=%s\n", dbPass)
	return nil
}

func randomHex(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

func printUsage() {
	fmt.Println(`haven-cli — Haven IAM administration

Commands:
  setup [--unattended]              Full unattended install (reads HAVEN_OWNER_* env vars)
  generate-secrets                  Print all required secrets as .env lines
  validate-config [--env-file FILE] Validate configuration before starting
  healthcheck [--addr URL]          Exit 0 if server is healthy (default: http://127.0.0.1:8080)
  factory-reset --confirm-destroy-all-data
                                    Wipe all data and reset to UNCLAIMED state`)
}
